/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package or;

import Manager.EmpLogin;
import Manager.MangLogin;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;

/**
 *
 * @author aq
 */
public class Fpage extends javax.swing.JFrame {


    /**
     * Creates new form MangLogin
     */
    public Fpage() {
        initComponents();
        setVisible(true);
    setSize(1280, 710);
       setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progress = new javax.swing.JProgressBar();
        enterChoice = new javax.swing.JTextField();
        sumbitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        progress.setBackground(new java.awt.Color(0, 0, 102));
        progress.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(progress);
        progress.setBounds(570, 620, 150, 40);
        progress.setVisible(false);

        enterChoice.setBackground(new java.awt.Color(253, 230, 230));
        enterChoice.setFont(new java.awt.Font("Hoefler Text", 3, 18)); // NOI18N
        enterChoice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterChoice.setText("  Enter choice here");
        enterChoice.setToolTipText("");
        enterChoice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 3));
        enterChoice.setCaretColor(new java.awt.Color(0, 204, 204));
        enterChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        enterChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterChoiceActionPerformed(evt);
            }
        });
        getContentPane().add(enterChoice);
        enterChoice.setBounds(560, 480, 180, 50);

        sumbitButton.setBackground(new java.awt.Color(204, 204, 204));
        sumbitButton.setFont(new java.awt.Font("Hoefler Text", 2, 14)); // NOI18N
        sumbitButton.setForeground(new java.awt.Color(153, 0, 51));
        sumbitButton.setText("SUBMIT");
        sumbitButton.setToolTipText("");
        sumbitButton.setActionCommand("");
        sumbitButton.setBorder(null);
        sumbitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumbitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sumbitButton);
        sumbitButton.setBounds(600, 560, 100, 40);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/or/1stpage.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1280, 730);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterChoiceActionPerformed
   
    
    
      
            
        
    }//GEN-LAST:event_enterChoiceActionPerformed

    private void sumbitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumbitButtonActionPerformed
progress.setVisible(true);
        progress.setMinimum(0);
        progress.setMaximum(100);
        progress.setStringPainted(true);
         for (int i = 0; i <= 100; i++) {
            final int currentValue = i;
         }
        
        String c = enterChoice.getText();
         if ("E".equals(c)|| "e".equals(c)){
             dispose();
             new EmpLogin().setVisible(true);}
         
        
             else if("M".equals(c)|| "m".equals(c)){
                         dispose();
                      new MangLogin().setVisible(true);}
             else if ("x".equals(c)|| "X".equals(c))
             dispose();
             
             else {
                 System.out.println("choice incorrect");
                     new Fpage().setVisible(true);
                 
             } 
                         
              
         
    }//GEN-LAST:event_sumbitButtonActionPerformed

         
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fpage().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enterChoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar progress;
    private javax.swing.JButton sumbitButton;
    // End of variables declaration//GEN-END:variables
}
